apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vehicure.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: vehicure-backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: vehicure-backend
  template:
    metadata:
      labels:
        app: vehicure-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "vehicure.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/system/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/system/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
